version: "3"
services:
  database:
    image: mysql
    restart: always
    container_name: BT-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: BTransaction
      MYSQL_USER: BTransactionApp
      MYSQL_PASSWORD: gkqrurrldnjs
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Seoul
    cap_add: #Security Config to avoid "mbind: Operation Not Permitted" Error
      - SYS_NICE
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --general-log=1
      - --general-log-file=/var/run/mysqld/query.log
      - --local-infile=1
      - --bulk_insert_buffer_size=256M
      - --innodb-rollback-on-timeout=TRUE
  bt-api:
    image: flaxinger/bt-api
    restart: always
    container_name: BT-api
    ports:
      - '8081:8081'
  bt-eureka:
    image: flaxinger/bt-eureka
    restart: always
    container_name: BT-eureka
    ports:
      - '8070:8070'
  bt-hystrix:
    image: flaxinger/bt-hystrix
    restart: always
    container_name: BT-hystrix
    ports:
      - '8080:8080'