version: "3"
services:
  database:
    image: mysql
    restart: always
    container_name: BT-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: BTransaction
      MYSQL_USER: BTransactionApp
      MYSQL_PASSWORD: gkqrurrldnjs
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Seoul
    cap_add: #Security Config to avoid "mbind: Operation Not Permitted" Error
      - SYS_NICE
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --general-log=1
      - --general-log-file=/var/log/mysql/query.log
