spring:
  application:
    name: eureka
server:
  port: 8070
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

