spring:
  application:
    name: bank-transaction
  datasource:
    url: jdbc:mysql://localhost:3306/BTransaction?characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&serverTimezone=Asia/Seoul
    username: BTransactionApp
    password: gkqrurrldnjs
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 2000
          batch_versioned_data: true
          generate_statistics: true
        show_sql: false
    database: mysql
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
server:
  port: 8081
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost